spring:
  profiles:
    active: development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
---
spring:
  profiles: development
  application:
    name: api-provider
#eureka客户端
server:
  port: 8762
eureka:
# 定义了renews 和renews threshold的比值，默认值为0.85,本地设置0.49
  server:
    renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
  client:
    #是否将自身注册
    register-with-eureka: true
    #FetchRegistry此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    #此处false，因为自己是服务端
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/