spring:
  profiles:
    active: development
server:
  port: 8081
  compression:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
mybatis:
  config-location: classpath:/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: io.omnidata.odmpapi.entity           # 定义所有操作类的别名所在包
  mapper-locations: classpath*:/mapper/*.xml
---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:mem:odmp;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS odmp\;SET SCHEMA odmp
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console
logging:
  path: .
  file: output.log
---
spring:
  profiles: testing
logging:
  path: /home/app/odmp/log
  file: output.log
---
spring:
  profiles: production
logging:
  path: /home/app/odmp/log
  file: output.log
